// Generated by Proven Mist Compiler
// THEOREM: This C code has equivalent semantics to the source
// PROOF: By structural induction on the AST

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <stdbool.h>

int main(void) {
    // Initialize RNG for stochastic semantics
    srand(time(NULL));

    // Blah statement
    printf("%s\n", "🎲 Let's play dice! 🎲");

    // Blah statement
    printf("%s\n", "");

    // Maybe declaration: die1
    int die1 = 0;
    bool die1_is_null = false;
    if (rand() % 2 == 0) {
        die1 = 6;
        printf("maybe die1 = %d\n", die1);
    } else {
        die1_is_null = true;
        printf("maybe die1 = null\n");
    }

    // Maybe declaration: die2
    int die2 = 0;
    bool die2_is_null = false;
    if (rand() % 2 == 0) {
        die2 = 6;
        printf("maybe die2 = %d\n", die2);
    } else {
        die2_is_null = true;
        printf("maybe die2 = null\n");
    }

    // Blah statement
    printf("%s\n", "Rolling dice...");

    // Blah statement
    printf("%s\n", "Die 1:");

    // Blah statement
    printf("%d\n", (die1_is_null ? 0 : die1));

    // Blah statement
    printf("%s\n", "Die 2:");

    // Blah statement
    printf("%d\n", (die2_is_null ? 0 : die2));

    // Blah statement
    printf("%s\n", "");

    // Blah statement
    printf("%s\n", "Your total:");

    // Blah statement
    printf("%d\n", ((die1_is_null ? 0 : die1) + (die2_is_null ? 0 : die2)));

    // Maybe declaration: winning_number
    int winning_number = 0;
    bool winning_number_is_null = false;
    if (rand() % 2 == 0) {
        winning_number = 7;
        printf("maybe winning_number = %d\n", winning_number);
    } else {
        winning_number_is_null = true;
        printf("maybe winning_number = null\n");
    }

    // Maybe declaration: bonus
    int bonus = 0;
    bool bonus_is_null = false;
    if (rand() % 2 == 0) {
        bonus = 10;
        printf("maybe bonus = %d\n", bonus);
    } else {
        bonus_is_null = true;
        printf("maybe bonus = null\n");
    }

    // Blah statement
    printf("%s\n", "");

    // Blah statement
    printf("%s\n", "The winning number today is:");

    // Blah statement
    printf("%d\n", (winning_number_is_null ? 0 : winning_number));

    // Blah statement
    printf("%s\n", "");

    // Blah statement
    printf("%s\n", "Your score with bonus:");

    // Blah statement
    printf("%d\n", (((die1_is_null ? 0 : die1) + (die2_is_null ? 0 : die2)) + (bonus_is_null ? 0 : bonus)));

    // Maybe declaration: bet
    int bet = 0;
    bool bet_is_null = false;
    if (rand() % 2 == 0) {
        bet = 20;
        printf("maybe bet = %d\n", bet);
    } else {
        bet_is_null = true;
        printf("maybe bet = null\n");
    }

    // Maybe declaration: multiplier
    int multiplier = 0;
    bool multiplier_is_null = false;
    if (rand() % 2 == 0) {
        multiplier = 3;
        printf("maybe multiplier = %d\n", multiplier);
    } else {
        multiplier_is_null = true;
        printf("maybe multiplier = null\n");
    }

    // Blah statement
    printf("%s\n", "");

    // Blah statement
    printf("%s\n", "You bet:");

    // Blah statement
    printf("%d\n", (bet_is_null ? 0 : bet));

    // Blah statement
    printf("%s\n", "With multiplier:");

    // Blah statement
    printf("%d\n", (multiplier_is_null ? 0 : multiplier));

    // Blah statement
    printf("%s\n", "Potential winnings:");

    // Blah statement
    printf("%d\n", (((bet_is_null ? 0 : bet) + (bet_is_null ? 0 : bet)) + (bet_is_null ? 0 : bet)));

    // Blah statement
    printf("%s\n", "");

    // Blah statement
    printf("%s\n", "Final payout calculation:");

    // Blah statement
    printf("%d\n", (((((die1_is_null ? 0 : die1) + (die2_is_null ? 0 : die2)) - (winning_number_is_null ? 0 : winning_number)) + (bonus_is_null ? 0 : bonus)) + (bet_is_null ? 0 : bet)));

    // Blah statement
    printf("%s\n", "");

    // Blah statement
    printf("%s\n", "Thanks for playing at the Maybe Casino!");

    // Blah statement
    printf("%s\n", "Where the house edge is quantum! 🎰");

    return 0;
}
