# rustfmt.toml - Stable features only

# Basic formatting
edition = "2021"
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
max_width = 100

# These are the only stable options available
use_field_init_shorthand = true
use_try_shorthand = true
force_explicit_abi = true
reorder_imports = true
reorder_modules = true
match_block_trailing_comma = true